import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dir=mkdtempSync(path.join(tmpdir(),'mothercare-test-'));
const port=Number(process.env.TEST_PORT||3187),env={...process.env,PORT:String(port),DB_PATH:path.join(dir,'test.sqlite')};
const seed=spawnSync(process.execPath,['server.mjs','--seed-demo'],{cwd:root,env,encoding:'utf8'});assert.equal(seed.status,0,seed.stderr);
let server;
async function start(){server=spawn(process.execPath,['server.mjs'],{cwd:root,env,stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',c=>reject(new Error('server exit '+c)));});}
async function stop(){await new Promise(r=>{server.once('exit',r);server.kill();});}
async function request(p,method='GET',body,token){const r=await fetch(`http://127.0.0.1:${port}/api${p}`,{method,headers:{'Content-Type':'application/json','X-MotherCare-Request':'1',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
const login=async(email)=>(await request('/login','POST',{email,password:'MotherCare2026!'})).data;
await test('MotherCare integrated server workflows',async t=>{await start();let mother,provider,admin,other,child,appointment,growth;
try{
await t.test('Reject unauthenticated health-record access',async()=>assert.equal((await request('/records/maternal')).status,401));
await t.test('Register, reject duplicate email and invalid password',async()=>{assert.equal((await request('/register','POST',{name:'Other Mother',email:'other@test.local',password:'MotherCare2026!'})).status,201);assert.equal((await request('/register','POST',{name:'Other',email:'other@test.local',password:'MotherCare2026!'})).status,409);assert.equal((await request('/register','POST',{name:'Other',email:'weak@test.local',password:'123'})).status,400);});
await t.test('Authenticate separate mother, provider and administrator sessions',async()=>{mother=await login('mother@demo.test');provider=await login('provider@demo.test');admin=await login('admin@demo.test');other=await login('other@test.local');assert.equal(mother.user.role,'mother');assert.equal(provider.user.role,'provider');assert.equal(admin.user.role,'admin');assert.notEqual(mother.token,provider.token);assert.equal((await request('/login','POST',{email:'mother@demo.test',password:'wrong'})).status,401);});
await t.test('Block public role escalation and admin clinical access',async()=>{const r=await request('/register','POST',{name:'Attacker',email:'role@test.local',password:'MotherCare2026!',role:'admin'});assert.equal(r.data.role,'mother');assert.equal((await request('/admin/users','GET',null,mother.token)).status,403);assert.equal((await request('/records/maternal','GET',null,admin.token)).status,403);});
await t.test('Save pregnancy and reject duplicate profile',async()=>{const b={edd:'2027-03-01',lmp:'2026-05-25',status:'pregnant'};assert.equal((await request('/records/pregnancy','POST',b,mother.token)).status,201);assert.equal((await request('/records/pregnancy','POST',b,mother.token)).status,409);});
await t.test('Schedule, validate time and reject appointment collision',async()=>{let r=await request('/records/appointments','POST',{date:'2026-09-23',time:'10:00',facility:'Test clinic',reason:'ANC visit',status:'scheduled',reminderHours:24},mother.token);assert.equal(r.status,201);appointment=r.data;assert.equal((await request('/records/appointments','POST',appointment,mother.token)).status,409);assert.equal((await request('/records/appointments','POST',{...appointment,time:'29:00'},mother.token)).status,400);});
await t.test('Generate appointment reminder and persist read state',async()=>{const r=await request('/notifications','GET',null,mother.token);assert.ok(r.data.some(n=>n.title.includes('ANC visit')));await request('/notifications/read','POST',{key:r.data[0].key},mother.token);assert.equal((await request('/notifications','GET',null,mother.token)).data[0].read,true);});
await t.test('Provider reviews assigned records but cannot read unassigned patient',async()=>{assert.equal((await request('/records/appointments?owner='+mother.user.id,'GET',null,provider.token)).data.length,1);assert.equal((await request('/records/appointments?owner='+other.user.id,'GET',null,provider.token)).status,403);assert.equal((await request('/records/appointments?owner='+mother.user.id,'GET',null,other.token)).status,403);});
await t.test('Update appointment and reject stale update',async()=>{const url='/records/appointments/'+appointment.id;const r=await request(url,'PUT',{...appointment,status:'completed'},mother.token);assert.equal(r.status,200);assert.equal(r.data.version,2);assert.equal((await request(url,'PUT',appointment,mother.token)).status,409);appointment=r.data;assert.equal((await request('/notifications','GET',null,mother.token)).data.length,0);});
await t.test('Validate maternal measures and save provider observation',async()=>{assert.equal((await request('/records/maternal','POST',{date:'2026-09-01',weight:-20},mother.token)).status,400);assert.equal((await request('/records/maternal','POST',{date:'2026-09-01',systolic:120},mother.token)).status,400);assert.equal((await request('/records/maternal?owner='+mother.user.id,'POST',{date:'2026-09-01',weight:65,systolic:120,diastolic:80,notes:'Test observation'},provider.token)).status,201);});
await t.test('Create child and enforce child-owner relationship',async()=>{child=(await request('/records/children','POST',{name:'Demo Baby',dob:'2026-01-01',sex:'female'},mother.token)).data;assert.ok(child.id);assert.equal((await request('/records/growth','POST',{childId:child.id,date:'2026-09-01',weight:8,height:68},other.token)).status,400);growth=(await request('/records/growth','POST',{childId:child.id,date:'2026-09-01',weight:8,height:68},mother.token)).data;assert.ok(growth.id);assert.equal((await request('/records/children/'+child.id,'DELETE',{version:1},mother.token)).status,409);});
await t.test('Save milestone and vaccination record',async()=>{assert.equal((await request('/records/milestones','POST',{childId:child.id,date:'2026-09-01',title:'Sat unsupported'},mother.token)).status,201);assert.equal((await request('/records/vaccines','POST',{childId:child.id,name:'Clinic-recorded dose',due:'2026-09-01',given:'2026-09-01'},mother.token)).status,201);});
await t.test('Medication reminder uses stored due date',async()=>{assert.equal((await request('/records/medications','POST',{name:'Test prescription',instructions:'As prescribed',nextDose:'2026-09-01T10:00:00+01:00',status:'active'},mother.token)).status,201);assert.ok((await request('/notifications','GET',null,mother.token)).data.some(n=>n.title.includes('Test prescription')));});
await t.test('Two-way communication and unauthorized recipient rejection',async()=>{assert.equal((await request('/messages','POST',{recipient:provider.user.id,body:'Question for my next visit'},mother.token)).status,201);assert.equal((await request('/messages','POST',{recipient:mother.user.id,body:'Please bring your records.'},provider.token)).status,201);assert.equal((await request('/messages','POST',{recipient:provider.user.id,body:'Unassigned'},other.token)).status,403);assert.equal((await request('/messages?peer='+provider.user.id,'GET',null,mother.token)).data.length,2);});
await t.test('Administrator manages education and rejects unsafe source links',async()=>{assert.equal((await request('/content/education','POST',{title:'Article',category:'Care',body:'Read clinic guidance',source:'javascript:alert(1)'},admin.token)).status,400);assert.equal((await request('/content/education','POST',{title:'Article',category:'Care',body:'Read clinic guidance',source:'https://www.who.int/'},admin.token)).status,200);assert.equal((await request('/content/education','POST',{},mother.token)).status,403);});
await t.test('Staff creation and account deactivation revoke sessions',async()=>{assert.equal((await request('/admin/users','POST',{name:'Staff Two',email:'staff2@test.local',password:'MotherCare2026!',role:'provider'},admin.token)).status,201);assert.equal((await request('/admin/users','PUT',{id:other.user.id,active:false},admin.token)).status,200);assert.equal((await request('/me','GET',null,other.token)).status,401);});
await t.test('Export excludes password hashes and other mothers',async()=>{const r=await request('/export','GET',null,mother.token);assert.equal(r.status,200);assert.ok(r.data.records.length>=7);assert.equal('password' in r.data.profile,false);assert.ok(r.data.records.every(x=>x.owner===mother.user.id));});
await t.test('Revoking provider assignment removes clinical access',async()=>{assert.equal((await request('/profile','PUT',{name:mother.user.name,providerId:''},mother.token)).status,200);assert.equal((await request('/records/maternal?owner='+mother.user.id,'GET',null,provider.token)).status,403);});
await t.test('Data and authenticated session survive server restart',async()=>{await stop();await start();const r=await request('/records/children','GET',null,mother.token);assert.equal(r.status,200);assert.equal(r.data[0].name,'Demo Baby');});
await t.test('Delete saved growth record and sign out',async()=>{assert.equal((await request('/records/growth/'+growth.id,'DELETE',{version:growth.version},mother.token)).status,200);assert.equal((await request('/logout','POST',{},mother.token)).status,200);assert.equal((await request('/me','GET',null,mother.token)).status,401);});
}finally{await stop();rmSync(dir,{recursive:true,force:true});}});
