import {chromium} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
process.chdir(path.dirname(path.dirname(fileURLToPath(import.meta.url))));
const browser=await chromium.launch({headless:true,args:[]});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
const screenshots='docs/screenshots';fs.mkdirSync(screenshots,{recursive:true});
const result=[];async function check(name,fn){await fn();result.push({name,status:'Passed'});console.log('PASS '+name);}
async function login(page,email){await page.goto('http://127.0.0.1:3000');await page.locator('#email').fill(email);await page.locator('#password').fill('MotherCare2026!');await page.locator('#authForm button.btn-primary').click();await page.locator('#app').waitFor({state:'visible'});await page.getByRole('heading',{name:/Hello,|Welcome,|Your administration/}).waitFor();}
async function go(page,key){await page.locator(`#nav [data-go="${key}"]`).click();await page.locator('main h1').waitFor();await page.waitForTimeout(150);}
async function add(values){await p.locator('#add').click();for(const [key,val]of Object.entries(values)){const input=p.locator('#f_'+key);if(await input.evaluate(e=>e.tagName==='SELECT'))await input.selectOption(val);else await input.fill(val);}await p.getByRole('button',{name:'Save record',exact:true}).click();await p.locator('#editor').waitFor({state:'hidden'});}
try{
await p.goto('http://127.0.0.1:3000');await p.screenshot({path:screenshots+'/01-login.png'});
await check('Login rejects wrong password',async()=>{await p.locator('#email').fill('mother@demo.test');await p.locator('#password').fill('wrong-password');await p.locator('#authForm button.btn-primary').click();await p.getByText('Email or password is incorrect.').waitFor();});
await check('Mother signs in',()=>login(p,'mother@demo.test'));
await check('Pregnancy profile creation',async()=>{await go(p,'pregnancy');await add({edd:'2026-12-17',lmp:'2026-03-12',status:'pregnant',notes:'Questions for my next visit'});await p.getByRole('heading',{name:'Expected delivery: 2026-12-17'}).waitFor();});
await check('Appointment creation and editing',async()=>{await go(p,'appointments');await add({date:'2026-09-25',time:'10:00',facility:'Academic Demonstration Clinic',provider:'Nurse Ada Demo',reason:'Routine antenatal visit',status:'scheduled',reminderHours:'48'});await p.locator('.edit').first().click();await p.locator('#f_notes').fill('Bring care card');await p.getByRole('button',{name:'Save record',exact:true}).click();await p.locator('#editor').waitFor({state:'hidden'});await p.getByText('Bring care card').waitFor();await p.screenshot({path:screenshots+'/03-appointments.png'});});
await check('Maternal measurement and chart',async()=>{await go(p,'maternal');await add({date:'2026-09-01',weight:'64',systolic:'115',diastolic:'75',temperature:'36.8',notes:'Recorded at clinic'});await add({date:'2026-09-20',weight:'65',systolic:'118',diastolic:'78',temperature:'36.7'});await p.locator('#trend').waitFor();await p.screenshot({path:screenshots+'/04-maternal.png'});});
await check('Child profile, growth and milestones',async()=>{await go(p,'children');await add({name:'Baby Demo',dob:'2026-01-10',sex:'female'});await go(p,'growth');let child=await p.evaluate(async()=>{const r=await fetch('/api/records/children',{headers:{Authorization:'Bearer '+sessionStorage.getItem('mc_token')}});return (await r.json())[0].id;});await add({childId:child,date:'2026-08-10',weight:'7.2',height:'64'});await add({childId:child,date:'2026-09-10',weight:'7.8',height:'66'});await p.screenshot({path:screenshots+'/05-growth.png'});await go(p,'milestones');await add({childId:child,date:'2026-09-10',title:'Sitting without support',notes:'Observation to discuss at clinic'});await go(p,'vaccines');await add({childId:child,name:'Clinic scheduled dose (demo)',due:'2026-09-25',notes:'Date entered from demonstration clinic card'});await p.screenshot({path:screenshots+'/06-vaccines.png'});});
await check('Medication reminders and notifications',async()=>{await go(p,'medications');await add({name:'Demo prescribed medicine',instructions:'Follow prescription from clinic',nextDose:'2026-09-24T08:00',status:'active'});await go(p,'notifications');await p.getByRole('heading',{name:'Medication reminder: Demo prescribed medicine'}).waitFor();await p.screenshot({path:screenshots+'/07-reminders.png'});});
await check('Persist records after reload and export download',async()=>{await p.reload();await p.getByRole('heading',{name:'Your reminders'}).waitFor();await go(p,'profile');const dl=p.waitForEvent('download');await p.locator('#export').click();const download=await dl;await download.saveAs('docs/ui-export.json');const data=JSON.parse(fs.readFileSync('docs/ui-export.json'));if(data.records.length<8)throw new Error('Export is incomplete');});
await check('Separate provider tab and two-way messaging',async()=>{await go(p,'messages');await p.locator('#compose textarea').fill('What should I bring for my visit?');await p.locator('#compose button').click();await p.getByText('What should I bring for my visit?',{exact:false}).waitFor();const q=await ctx.newPage();q.on('pageerror',e=>errors.push(e.message));await login(q,'provider@demo.test');await go(q,'patients');await q.locator('.select-patient').click();await q.getByText('Recorded at clinic').waitFor();await go(q,'messages');await q.locator('#compose textarea').fill('Please bring your care card and previous records.');await q.locator('#compose button').click();await q.getByText('Please bring your care card and previous records.',{exact:false}).waitFor();await p.reload();await p.getByText('Please bring your care card and previous records.',{exact:false}).waitFor();if(!await p.locator('#userRole').textContent().then(t=>t==='mother'))throw new Error('Tab session changed');await p.screenshot({path:screenshots+'/08-messages.png'});await q.close();});
await check('Administrator creates content and manages accounts',async()=>{const q=await ctx.newPage();await login(q,'admin@demo.test');await go(q,'admin');await q.getByRole('heading',{name:'User accounts'}).waitFor();await q.screenshot({path:screenshots+'/09-admin.png'});await go(q,'education');await q.locator('#add').click();await q.locator('#f_title').fill('Bring your clinic records');await q.locator('#f_category').fill('Clinic preparation');await q.locator('#f_body').fill('Keep your appointment card and previous health records together before your visit.');await q.locator('#f_source').fill('https://www.who.int/');await q.getByRole('button',{name:'Save record',exact:true}).click();await q.locator('#editor').waitFor({state:'hidden'});await q.getByRole('heading',{name:'Bring your clinic records'}).waitFor();await q.close();});
await check('Education and populated overview',async()=>{await go(p,'education');await p.getByRole('heading',{name:'Bring your clinic records'}).waitFor();await p.screenshot({path:screenshots+'/10-education.png'});await go(p,'home');await p.getByRole('heading',{name:'Hello, Amara.'}).waitFor();await p.screenshot({path:screenshots+'/02-dashboard.png'});});
await check('Mobile layout and navigation at 390px',async()=>{await p.setViewportSize({width:390,height:844});await p.screenshot({path:screenshots+'/11-mobile.png',fullPage:true});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Horizontal overflow');await p.locator('#menu').click();await p.locator('#nav [data-go="appointments"]').click();await p.getByRole('heading',{name:'Appointments',exact:true}).waitFor();await p.locator('#add').click();await p.locator('#editor').waitFor({state:'visible'});if(await p.locator('#editor').evaluate(e=>e.getBoundingClientRect().right>innerWidth))throw new Error('Modal overflow');await p.locator('#closeEditor').click();});
await check('No browser runtime errors',async()=>{if(errors.length)throw new Error(errors.join('\n'));});
}finally{fs.writeFileSync('docs/ui-test-results.json',JSON.stringify({browser:await browser.version(),viewport:'1440x1000 and 390x844',executedAt:new Date().toISOString(),tests:result,errors},null,2));await browser.close();}
