import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {mkdirSync,readFileSync,existsSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const ROOT=path.dirname(fileURLToPath(import.meta.url));
const file=process.env.DB_PATH||path.join(ROOT,'data','mothercare.sqlite');
mkdirSync(path.dirname(file),{recursive:true});
const db=new DatabaseSync(file);
db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('mother','provider','admin')),active INTEGER NOT NULL DEFAULT 1,profile TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id) ON DELETE CASCADE,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,owner TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL,child_id TEXT REFERENCES records(id) ON DELETE RESTRICT,data TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,created TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS records_owner_kind ON records(owner,kind);
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,sender TEXT REFERENCES users(id),recipient TEXT REFERENCES users(id),body TEXT NOT NULL,created TEXT NOT NULL,seen INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS messages_recipient ON messages(recipient,created);
CREATE TABLE IF NOT EXISTS content(id TEXT PRIMARY KEY,kind TEXT NOT NULL,data TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS acknowledgements(user_id TEXT REFERENCES users(id),key TEXT NOT NULL,PRIMARY KEY(user_id,key));
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,user_id TEXT,event TEXT NOT NULL,entity TEXT,created TEXT NOT NULL);`);
const sql=(q,...args)=>db.prepare(q).all(...args);
const one=(q,...args)=>db.prepare(q).get(...args);
const run=(q,...args)=>db.prepare(q).run(...args);
const now=()=>new Date().toISOString();
const hash=s=>createHash('sha256').update(s).digest('hex');
function passwordHash(s){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(s,salt,64).toString('hex');}
function passwordOK(s,h){const [salt,v]=h.split(':');return timingSafeEqual(scryptSync(s,salt,64),Buffer.from(v,'hex'));}
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function text(v,name,max=500,required=false){if(v==null)v='';if(typeof v!=='string'||v.length>max)fail(`${name} must be text of at most ${max} characters.`);v=v.trim();if(required&&!v)fail(`${name} is required.`);return v;}
function date(v,name,required=false){v=text(v,name,10,required);if(v&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))fail(`${name} is invalid.`);return v;}
function numeric(v,name,min,max){if(v===''||v==null)return '';if(!Number.isFinite(Number(v))||Number(v)<min||Number(v)>max)fail(`${name} must be between ${min} and ${max}.`);return Number(v);}
function choice(v,name,options){if(!options.includes(v))fail(`Invalid ${name}.`);return v;}
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,active:!!u.active,profile:JSON.parse(u.profile)});
const audit=(u,e,id='')=>run('INSERT INTO audit(user_id,event,entity,created) VALUES(?,?,?,?)',u?.id||null,e,id,now());
function createUser(b,role='mother'){const name=text(b.name,'Name',100,true),email=text(b.email,'Email',150,true).toLowerCase(),p=text(b.password,'Password',128,true);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('Enter a valid email.');if(p.length<10)fail('Use at least 10 characters for your password.');if(one('SELECT id FROM users WHERE email=?',email))fail('An account already uses this email.',409);const id=randomUUID();run('INSERT INTO users(id,name,email,password,role) VALUES(?,?,?,?,?)',id,name,email,passwordHash(p),role);return one('SELECT * FROM users WHERE id=?',id);}
const recordKinds=['pregnancy','appointments','maternal','children','growth','milestones','vaccines','medications'];
function validate(kind,b,owner){const o={};const fields={pregnancy:['lmp','edd','status','notes'],appointments:['date','time','facility','provider','reason','notes','status','reminderHours'],maternal:['date','weight','systolic','diastolic','temperature','glucose','haemoglobin','notes'],children:['name','dob','sex','notes'],growth:['date','weight','height','head','notes'],milestones:['date','title','notes'],vaccines:['name','due','given','facility','notes'],medications:['name','instructions','nextDose','status','notes']}[kind];if(!fields)fail('Unknown record type.');
 for(const f of fields)o[f]=text(String(b[f]??''),f,f==='notes'?3000:300);
 for(const f of ['date','lmp','edd','dob','due','given'])if(f in o)o[f]=date(o[f],f,['date','dob','due','edd'].includes(f));
 for(const f of ['name','title','facility','reason','instructions'])if(f in o&&!(kind==='vaccines'&&f==='facility'))o[f]=text(o[f],f,300,true);
 const today=now().slice(0,10);for(const f of ['dob','given','date'])if(o[f]&&o[f]>today&&!(kind==='appointments'&&f==='date'))fail(`${f} cannot be in the future.`);
 if(kind==='pregnancy'){o.status=choice(o.status,'pregnancy status',['pregnant','postnatal','closed']);if(o.lmp&&o.lmp>today)fail('Last menstrual period cannot be in the future.');if(o.lmp&&o.edd<=o.lmp)fail('Expected delivery must follow the last menstrual period.');}
 if(kind==='appointments'){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(o.time))fail('Enter a valid appointment time.');o.status=choice(o.status,'appointment status',['scheduled','completed','cancelled']);o.reminderHours=numeric(o.reminderHours,'Reminder hours',0,168);}
 const ranges={weight:[0.1,500],height:[10,250],head:[10,100],systolic:[30,300],diastolic:[20,200],temperature:[25,45],glucose:[0.1,50],haemoglobin:[1,25]};for(const [f,r] of Object.entries(ranges))if(f in o)o[f]=numeric(o[f],f,...r);
 if(kind==='maternal'&&!['weight','systolic','temperature','glucose','haemoglobin'].some(f=>o[f]!==''))fail('Enter at least one measurement.');
 if(kind==='maternal'&&((o.systolic==='')!==(o.diastolic==='')))fail('Enter both blood pressure values.');
 if(kind==='growth'&&(o.weight===''||o.height===''))fail('Weight and length/height are required.');
 if(kind==='children')o.sex=choice(o.sex,'sex',['female','male','unspecified']);
 if(kind==='medications'){o.status=choice(o.status,'medication status',['active','completed']);if(!Number.isFinite(Date.parse(o.nextDose)))fail('Next reminder date and time are required.');o.nextDose=new Date(o.nextDose).toISOString();}
 if(['growth','milestones','vaccines'].includes(kind)){const child=one("SELECT * FROM records WHERE id=? AND owner=? AND kind='children'",b.childId,owner);if(!child)fail('Select a child belonging to this record owner.');o.childId=child.id;const dob=JSON.parse(child.data).dob;if((o.date&&o.date<dob)||(o.given&&o.given<dob)||(o.due&&o.due<dob))fail('A child record cannot precede their date of birth.');}
 return o;
}
function record(r){return {...JSON.parse(r.data),id:r.id,owner:r.owner,kind:r.kind,version:r.version,created:r.created};}
function target(u,id){if(u.role==='admin')fail('Administrators cannot access clinical records.',403);id=id||u.id;if(u.role==='mother'&&id!==u.id)fail('Access denied.',403);if(u.role==='provider'){const p=one("SELECT * FROM users WHERE id=? AND role='mother' AND active=1",id);if(!p||JSON.parse(p.profile).providerId!==u.id)fail('Only assigned patients are accessible.',403);}return id;}
function notifications(u){let list=[];if(u.role==='mother'){const rows=sql('SELECT * FROM records WHERE owner=?',u.id).map(record),t=Date.now();for(const r of rows){let due,label;if(r.kind==='appointments'&&r.status==='scheduled'){due=Date.parse(r.date+'T'+r.time+'+01:00');if(due-t>Number(r.reminderHours===''?24:r.reminderHours)*3600000)continue;label=`ANC appointment: ${r.reason}`;}if(r.kind==='vaccines'&&!r.given){due=Date.parse(r.due+'T09:00:00+01:00');if(due-t>86400000)continue;label=`Immunization: ${r.name}`;}if(r.kind==='medications'&&r.status==='active'){due=Date.parse(r.nextDose);if(due>t)continue;label=`Medication reminder: ${r.name}`;}if(label)list.push({key:r.id+':'+due,title:label,detail:`${due<t?'Due / overdue':'Upcoming'} · ${new Date(due).toLocaleString('en-GB',{timeZone:'Africa/Lagos'})}`,page:r.kind});}}
 for(const m of sql('SELECT m.*,u.name FROM messages m JOIN users u ON u.id=m.sender WHERE recipient=? AND seen=0',u.id))list.push({key:'message:'+m.id,title:'Message from '+m.name,detail:m.created,page:'messages'});
 const seen=new Set(sql('SELECT key FROM acknowledgements WHERE user_id=?',u.id).map(r=>r.key));return list.map(n=>({...n,read:seen.has(n.key)}));}
function contentData(kind,b){if(kind==='education'){const url=text(b.source,'Source URL',600,true);if(!/^https:\/\//.test(url))fail('Source must be an HTTPS link.');return {title:text(b.title,'Title',200,true),category:text(b.category,'Category',80,true),body:text(b.body,'Article',10000,true),source:url};}if(kind==='facilities')return {name:text(b.name,'Name',200,true),address:text(b.address,'Address',500,true),phone:text(b.phone,'Phone',30,true),hours:text(b.hours,'Opening hours',150,true)};fail('Unknown content type.');}
// Educational summaries; dates and treatment schedules are entered from the care provider.
if(!one("SELECT id FROM content WHERE kind='education'")){
 const source='https://www.who.int/tools/your-life-your-health/life-phase/pregnancy--birth-and-after-childbirth/keeping-well-during-pregnancy-and-after-childbirth';
 for(const [title,category,body] of [['Preparing for your antenatal visit','Antenatal care','Keep your clinic dates and bring your care records. Write down questions and new symptoms to discuss with your midwife or doctor.'],['Planning for childbirth','Birth preparation','Discuss where you will give birth with your care team. Plan transport, support, and how to reach a health facility if urgent care is needed.'],['Know when to seek urgent care','Warning signs','Bleeding, severe headache or severe abdominal pain during pregnancy need urgent medical attention. Seek care immediately rather than waiting for an app reply.'],['Support after childbirth','Postnatal care','Follow up with your care team after birth for both you and your baby. Ask for help with recovery, feeding and any physical or emotional concerns.']])run('INSERT INTO content(id,kind,data) VALUES(?,?,?)',randomUUID(),'education',JSON.stringify({title,category,body,source}));
}
if(process.argv.includes('--seed-demo')){for(const [name,email,role] of [['Amara Demo','mother@demo.test','mother'],['Nurse Ada Demo','provider@demo.test','provider'],['Administrator Demo','admin@demo.test','admin']])if(!one('SELECT id FROM users WHERE email=?',email))createUser({name,email,password:'MotherCare2026!'},role);const p=one('SELECT id FROM users WHERE email=?','provider@demo.test');run('UPDATE users SET profile=? WHERE email=?',JSON.stringify({providerId:p.id,phone:'',state:'Delta',lga:'',emergencyName:'',emergencyPhone:''}),'mother@demo.test');console.log('Demo accounts created. Password: MotherCare2026! See README.md.');db.close();process.exit(0);}
const limits=new Map();
const server=http.createServer(async(req,res)=>{
 const send=(status,data,headers={})=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data));};
 try{
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');
 const url=new URL(req.url,'http://localhost'),p=url.pathname,method=req.method;
 if(!p.startsWith('/api/')){if(method!=='GET')return send(405,{error:'Method not allowed'});let f=p==='/'?'index.html':decodeURIComponent(p).slice(1);if(f.includes('..')||f.includes('\\'))return send(404,{error:'Not found'});const full=path.join(ROOT,'public',f);if(!existsSync(full))return send(404,{error:'Not found'});const ext=path.extname(full);res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.woff':'font/woff','.svg':'image/svg+xml'}[ext]||'application/octet-stream'});return res.end(readFileSync(full));}
 let b={};if(!['GET','HEAD'].includes(method)){if(req.headers['x-mothercare-request']!=='1')fail('Request header required.',403);const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)fail('Cross-origin request rejected.',403);let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100000)fail('Request too large.',413);}try{b=raw?JSON.parse(raw):{};}catch{fail('Invalid JSON.');}if(!b||typeof b!=='object'||Array.isArray(b))fail('JSON object required.');}
 if(p==='/api/register'&&method==='POST'){const u=createUser(b);audit(u,'REGISTER');return send(201,publicUser(u));}
 if(p==='/api/login'&&method==='POST'){const key=req.socket.remoteAddress;const l=limits.get(key);if(l&&l.until>Date.now()&&l.count>=15)fail('Too many attempts. Try again in 15 minutes.',429);const u=one('SELECT * FROM users WHERE email=?',String(b.email||'').toLowerCase().trim());if(!u||!u.active||!passwordOK(text(b.password,'Password',128),u.password)){limits.set(key,{count:(l?.until>Date.now()?l.count:0)+1,until:Date.now()+900000});fail('Email or password is incorrect.',401);}limits.delete(key);const token=randomBytes(32).toString('hex');run('DELETE FROM sessions WHERE expires<?',Date.now());run('INSERT INTO sessions VALUES(?,?,?)',hash(token),u.id,Date.now()+12*3600000);audit(u,'LOGIN');return send(200,{user:publicUser(u),token});}
 const token=(req.headers.authorization||'').replace(/^Bearer /,'');const u=one('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>? AND u.active=1',hash(token),Date.now());if(!u)fail('Please sign in again.',401);
 if(p==='/api/logout'&&method==='POST'){run('DELETE FROM sessions WHERE token=?',hash(token));return send(200,{ok:true});}
 if(p==='/api/me'&&method==='GET')return send(200,publicUser(u));
 if(p==='/api/password'&&method==='POST'){if(!passwordOK(text(b.current,'Current password',128),u.password))fail('Current password is incorrect.');const password=text(b.password,'New password',128,true);if(password.length<10)fail('Use at least 10 characters.');run('UPDATE users SET password=? WHERE id=?',passwordHash(password),u.id);run('DELETE FROM sessions WHERE user_id=? AND token<>?',u.id,hash(token));audit(u,'PASSWORD_CHANGED');return send(200,{ok:true});}
 if(p==='/api/profile'&&method==='PUT'){const profile={};for(const f of ['phone','state','lga','emergencyName','emergencyPhone'])profile[f]=text(b[f],f,150);profile.providerId=text(b.providerId,'Provider',100);if(u.role!=='mother')profile.providerId='';if(profile.providerId&&!one("SELECT id FROM users WHERE id=? AND role='provider' AND active=1",profile.providerId))fail('Select an active provider.');const name=text(b.name,'Name',100,true);run('UPDATE users SET name=?,profile=? WHERE id=?',name,JSON.stringify(profile),u.id);audit(u,'PROFILE_UPDATED');return send(200,publicUser(one('SELECT * FROM users WHERE id=?',u.id)));}
 if(p==='/api/providers'&&method==='GET')return send(200,sql("SELECT id,name FROM users WHERE role='provider' AND active=1"));
 if(p==='/api/patients'&&method==='GET'){if(u.role!=='provider')fail('Access denied.',403);return send(200,sql("SELECT * FROM users WHERE role='mother' AND active=1").filter(x=>JSON.parse(x.profile).providerId===u.id).map(publicUser));}
 if(p==='/api/notifications'&&method==='GET')return send(200,notifications(u));
 if(p==='/api/notifications/read'&&method==='POST'){const key=text(b.key,'Notification key',150,true);run('INSERT OR IGNORE INTO acknowledgements VALUES(?,?)',u.id,key);return send(200,{ok:true});}
 if(p==='/api/export'&&method==='GET'){const owner=target(u,url.searchParams.get('owner'));audit(u,'EXPORT_RECORD',owner);return send(200,{exportedAt:now(),profile:publicUser(one('SELECT * FROM users WHERE id=?',owner)),records:sql('SELECT * FROM records WHERE owner=? ORDER BY created',owner).map(record)});}
 const rm=p.match(/^\/api\/records\/([a-z]+)(?:\/([^/]+))?$/);if(rm){const [,kind,id]=rm;if(!recordKinds.includes(kind))fail('Unknown module.',404);const owner=target(u,url.searchParams.get('owner'));if(method==='GET')return send(200,sql('SELECT * FROM records WHERE owner=? AND kind=? ORDER BY created DESC',owner,kind).map(record));if(u.role==='provider'&&['pregnancy','children'].includes(kind))fail('This profile is maintained by the mother.',403);const old=id?one('SELECT * FROM records WHERE id=? AND owner=? AND kind=?',id,owner,kind):null;if(id&&!old)fail('Record not found.',404);
 if(method==='DELETE'&&old){if(b.version!==old.version)fail('This record changed. Refresh and retry.',409);if(one('SELECT id FROM records WHERE child_id=?',id))fail('Remove this child’s linked growth, milestone and vaccine records first.',409);run('DELETE FROM records WHERE id=?',id);audit(u,'DELETE_'+kind,id);return send(200,{ok:true});}
 if(!['POST','PUT'].includes(method)||(method==='PUT'&&!id)||(method==='POST'&&id))fail('Method not allowed.',405);if(old&&old.version!==b.version)fail('This record changed. Refresh and retry.',409);const data=validate(kind,b,owner);if(kind==='pregnancy'&&!old&&one("SELECT id FROM records WHERE owner=? AND kind='pregnancy'",owner))fail('Edit your existing pregnancy profile.',409);if(kind==='appointments'&&data.status==='scheduled'){const conflict=sql("SELECT * FROM records WHERE owner=? AND kind='appointments' AND id<>?",owner,id||'').map(record).find(r=>r.date===data.date&&r.time===data.time&&r.status==='scheduled');if(conflict)fail('You already have an appointment at this date and time.',409);}
 const rid=id||randomUUID();if(old)run('UPDATE records SET data=?,child_id=?,version=version+1 WHERE id=?',JSON.stringify(data),data.childId||null,rid);else run('INSERT INTO records(id,owner,kind,child_id,data,created) VALUES(?,?,?,?,?,?)',rid,owner,kind,data.childId||null,JSON.stringify(data),now());audit(u,(old?'UPDATE_':'CREATE_')+kind,rid);return send(old?200:201,record(one('SELECT * FROM records WHERE id=?',rid)));}
 if(p==='/api/messages'&&method==='GET'){const peer=url.searchParams.get('peer');let msgs=sql('SELECT m.*,u.name AS senderName FROM messages m JOIN users u ON u.id=m.sender WHERE (sender=? OR recipient=?) ORDER BY created',u.id,u.id);if(peer){msgs=msgs.filter(m=>m.sender===peer||m.recipient===peer);run('UPDATE messages SET seen=1 WHERE recipient=? AND sender=?',u.id,peer);}return send(200,msgs);}
 if(p==='/api/messages'&&method==='POST'){const recipient=text(b.recipient,'Recipient',100,true),r=one('SELECT * FROM users WHERE id=? AND active=1',recipient);const connected=r&&((u.role==='mother'&&r.role==='provider'&&JSON.parse(u.profile).providerId===r.id)||(u.role==='provider'&&r.role==='mother'&&JSON.parse(r.profile).providerId===u.id));if(!connected)fail('Messages require an assigned mother–provider relationship.',403);const id=randomUUID();run('INSERT INTO messages(id,sender,recipient,body,created) VALUES(?,?,?,?,?)',id,u.id,recipient,text(b.body,'Message',4000,true),now());audit(u,'MESSAGE_SENT',id);return send(201,{id});}
 const cm=p.match(/^\/api\/content\/(education|facilities)(?:\/([^/]+))?$/);if(cm){const [,kind,id]=cm;if(method==='GET')return send(200,sql('SELECT * FROM content WHERE kind=?',kind).map(r=>({...JSON.parse(r.data),id:r.id,version:r.version})));if(u.role!=='admin')fail('Administrator access required.',403);const old=id?one('SELECT * FROM content WHERE id=? AND kind=?',id,kind):null;if(id&&!old)fail('Content not found.',404);if(old&&b.version!==old.version)fail('Content changed. Refresh and retry.',409);if(method==='DELETE'&&old){run('DELETE FROM content WHERE id=?',id);return send(200,{ok:true});}if(!['POST','PUT'].includes(method)||(method==='PUT'&&!id))fail('Method not allowed.',405);const data=contentData(kind,b),rid=id||randomUUID();if(old)run('UPDATE content SET data=?,version=version+1 WHERE id=?',JSON.stringify(data),rid);else run('INSERT INTO content(id,kind,data) VALUES(?,?,?)',rid,kind,JSON.stringify(data));audit(u,'CONTENT_UPDATED',rid);return send(200,{...data,id:rid,version:old?old.version+1:1});}
 if(p.startsWith('/api/admin/')){if(u.role!=='admin')fail('Administrator access required.',403);if(p==='/api/admin/users'&&method==='GET')return send(200,sql('SELECT * FROM users ORDER BY name').map(({profile,...x})=>publicUser({...x,profile:'{}'})));if(p==='/api/admin/users'&&method==='POST'){const role=choice(b.role,'role',['provider','admin']);const nu=createUser(b,role);audit(u,'STAFF_CREATED',nu.id);return send(201,publicUser(nu));}if(p==='/api/admin/users'&&method==='PUT'){const id=text(b.id,'User',100,true);if(id===u.id)fail('You cannot deactivate your own account.');if(typeof b.active!=='boolean')fail('Active must be true or false.');if(!one('SELECT id FROM users WHERE id=?',id))fail('User not found.',404);run('UPDATE users SET active=? WHERE id=?',b.active?1:0,id);if(!b.active)run('DELETE FROM sessions WHERE user_id=?',id);audit(u,'USER_STATUS_CHANGED',id);return send(200,{ok:true});}if(p==='/api/admin/audit'&&method==='GET')return send(200,sql('SELECT * FROM audit ORDER BY id DESC LIMIT 200'));}
 fail('Endpoint not found.',404);
 }catch(e){if(!e.status)console.error(e);send(e.status||500,{error:e.status?e.message:'The server could not complete this request.'});}
});
server.listen(Number(process.env.PORT||3000),process.env.HOST||'127.0.0.1',()=>console.log(`MotherCare NG ready at http://${process.env.HOST||'localhost'}:${process.env.PORT||3000}`));
